### ISSUE TITLE
2.0.3: lasinfo crashes on sample data

### ISSUE THREAD

**Issue by landryb** [LAStools/LAStools#188]
running lasinfo on the provided sample.laz blows:
```
    GeoDoubleParamsTag (number of doubles 5)
      19 0 0.9993 500000 -5.3e+06 
the header is followed by 2 user-defined bytes
LASzip compression (version 2.2r0 c2 50000): POINT10 2 GPSTIME11 2
reporting minimum and maximum for all LAS point record entries ...

Program received signal SIGSEGV, Segmentation fault.
0x00000aa25a641af0 in LASpoint::get_Z (this=0x74d3c1280ff8) at /usr/obj/ports/LAStools-2.0.3/LAStools-2.0.3/src/../LASzip/src/laspoint.hpp:529
529         if ((quantizer == nullptr) || (quantizer->z_from_attrib < 0)) {
(gdb) bt
#0  0x00000aa25a641af0 in LASpoint::get_Z (this=0x74d3c1280ff8) at /usr/obj/ports/LAStools-2.0.3/LAStools-2.0.3/src/../LASzip/src/laspoint.hpp:529
#1  0x00000aa25a6a33cf in LASsummary::add (this=0x74d3c127e5d0, point=0xaa50b466c58) at /usr/obj/ports/LAStools-2.0.3/LAStools-2.0.3/LASlib/src/lasutility.cpp:247
#2  0x00000aa25a63dd34 in main (argc=2, argv=<optimized out>) at /usr/obj/ports/LAStools-2.0.3/LAStools-2.0.3/src/lasinfo.cpp:4155
(gdb) p quantizer
$1 = (const LASquantizer *) 0x8a7d52469dea8d25
(gdb) p *quantizer
Cannot access memory at address 0x8a7d52469dea8d25
```
looks like memory corruption... 2.0.2 is fine, so i guess it has to do with the new z from attribute feature. That's on OpenBSD.

**Comment by landryb** [comment]
looking with gdb, something is definitely weird:
```
(gdb) up
#1  0x00000982ea1c93cf in LASsummary::add (this=0x6fdb27d49e20, point=0x985c85d3758) at /usr/obj/ports/LAStools-2.0.3/LAStools-2.0.3/LASlib/src/lasutility.cpp:247
247         if (point->get_Z() < min.get_Z()) min.set_Z(point->get_Z());
(gdb) p point
$1 = (const LASpoint *) 0x985c85d3758
(gdb) p *point
$2 = {X = 30922712, Y = 614349659, Z = 46674, intensity = 112, return_number = 1 '\001', number_of_returns = 2 '\002', scan_direction_flag = 0 '\000', edge_of_flight_line = 0 '\000', 
  classification = 5 '\005', synthetic_flag = 0 '\000', keypoint_flag = 0 '\000', withheld_flag = 0 '\000', scan_angle_rank = -10 '\366', user_data = 78 'N', point_source_ID = 5, 
  extended_scan_angle = 0, extended_point_type = 0 '\000', extended_scanner_channel = 0 '\000', extended_classification_flags = 0 '\000', extended_classification = 0 '\000', 
  extended_return_number = 1 '\001', extended_number_of_returns = 1 '\001', deleted_flag = 0 '\000', dummy = "\337", <incomplete sequence \337>, gps_time_change = 223, 
  gps_time = 11570.850897, rgb = {0, 0, 0, 0}, wavepacket = {data = '\000' <repeats 28 times>}, extra_bytes = 0x0, quantizer = 0x985c85d3510, coordinates = {-6.6776141455008222e+153, 
    -6.6776141455008222e+153, -6.6776141455008222e+153}, attributer = 0x985c85d3548, point = 0x985c85d5a60, have_gps_time = true, have_rgb = false, have_nir = false, 
  have_wavepacket = false, extra_bytes_number = 0, total_point_size = 28, rgb_bits_depth = 0 '\000', num_items = 2, items = 0x985c85f92e0}
(gdb) p *(point->quantizer)
$3 = {x_scale_factor = 0.01, y_scale_factor = 0.01, z_scale_factor = 0.01, x_offset = 0, y_offset = 0, z_offset = 0, z_from_attrib = -1}
(gdb) down
#0  0x00000982ea167af0 in LASpoint::get_Z (this=0x6fdb27d4c848) at /usr/obj/ports/LAStools-2.0.3/LAStools-2.0.3/src/../LASzip/src/laspoint.hpp:529
529         if ((quantizer == nullptr) || (quantizer->z_from_attrib < 0)) {
(gdb) p quantizer->z_from_attrib
Cannot access memory at address 0x1b08867f72a374d4
```

**Comment by landryb** [comment]
thanks @BB-Heidelberg can confirm that it fixes my testcase
